// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOf7W1W03qLjG4nK3ONbNsWWLbA9qzx8',
    appId: '1:213555936927:web:2d356a8cf1afd30a5fecaa',
    messagingSenderId: '213555936927',
    projectId: 'crud-application-20f85',
    authDomain: 'crud-application-20f85.firebaseapp.com',
    storageBucket: 'crud-application-20f85.appspot.com',
    measurementId: 'G-5ZH615XZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmrKc3Q05mE_UOWTSVUDnELmqtoIbCMaw',
    appId: '1:213555936927:android:521c9ee37b8db4345fecaa',
    messagingSenderId: '213555936927',
    projectId: 'crud-application-20f85',
    storageBucket: 'crud-application-20f85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgpJzb60Nr6WHU8vVh7Q8xFUoz6p8M8a8',
    appId: '1:213555936927:ios:55333fe90a17202f5fecaa',
    messagingSenderId: '213555936927',
    projectId: 'crud-application-20f85',
    storageBucket: 'crud-application-20f85.appspot.com',
    iosBundleId: 'com.example.crudApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgpJzb60Nr6WHU8vVh7Q8xFUoz6p8M8a8',
    appId: '1:213555936927:ios:55333fe90a17202f5fecaa',
    messagingSenderId: '213555936927',
    projectId: 'crud-application-20f85',
    storageBucket: 'crud-application-20f85.appspot.com',
    iosBundleId: 'com.example.crudApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvOf7W1W03qLjG4nK3ONbNsWWLbA9qzx8',
    appId: '1:213555936927:web:954413f8e22096605fecaa',
    messagingSenderId: '213555936927',
    projectId: 'crud-application-20f85',
    authDomain: 'crud-application-20f85.firebaseapp.com',
    storageBucket: 'crud-application-20f85.appspot.com',
    measurementId: 'G-KJ22LNSM5G',
  );
}
